# Generated by Django 3.1 on 2021-09-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
