# Generated by Django 3.1 on 2021-09-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('orders', '0003_auto_20210923_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='variation',
        ),
        migrations.AddField(
            model_name='order_product',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
